### ISSUE TITLE
Permanent segfault with notmuch-0.25

### ISSUE THREAD

**Issue by evgkrsk** [aperezdc/notmuch-addrlookup-c#18]
v8-4-g88f156d give me permanent segfault when linked with libnotmuch-0.25

Backtrace from coredump is not very informative to me:
```
Core was generated by `notmuch-addrlookup ldv'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      }
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f795c8a328a in __GI_abort () at abort.c:89
#2  0x00007f795c19a10c in talloc_abort (reason=0x7f795c1a5d58 "Bad talloc magic value - unknown value") at ../talloc.c:426
#3  0x00007f795c19e889 in talloc_abort_unknown_value () at ../talloc.c:444
#4  talloc_chunk_from_ptr (ptr=0x658fb0) at ../talloc.c:463
#5  __talloc_with_prefix (tc_ret=<synthetic pointer>, prefix_len=0, size=<optimized out>, context=<optimized out>) at ../talloc.c:678
#6  __talloc (tc=<synthetic pointer>, size=<optimized out>, context=0x658fb0) at ../talloc.c:739
#7  _vasprintf_tc (t=<optimized out>, fmt=0x7f795cf72800 "%s%s", ap=ap@entry=0x7fffc5222538) at ../talloc.c:2523
#8  0x00007f795c19ea89 in talloc_vasprintf (t=<optimized out>, fmt=<optimized out>, ap=ap@entry=0x7fffc5222538) at ../talloc.c:2540
#9  0x00007f795c19eb37 in talloc_asprintf (t=t@entry=0x658fb0, fmt=fmt@entry=0x7f795cf72800 "%s%s") at ../talloc.c:2558
#10 0x00007f795cf6e788 in _notmuch_query_count_documents (query=0x658fb0, type=0x7f795cf73db8 "mail", count_out=0x7fffc5222814) at lib/query.cc:620
#11 0x0000000000401cd1 in main ()
(gdb) 
```

**Comment by aperezdc** [comment]
I have not seent this myself, is the issue still happening?
